[build]
builder = "NIXPACKS"

[phases.setup]
# This explicitly forces Railway to load both Node.js and FFmpeg binaries
nixPkgs = ["nodePackages.npm", "nodejs", "ffmpeg"]

[deploy]
root = "server"
watchPatterns = ["server/**"]
startCommand = "node index.js"
