[build]
builder = "NIXPACKS"

[phases.setup]
# This is the exact package syntax Nixpacks uses to bundle Node.js and FFmpeg
nixPkgs = ["...", "nodejs-20_x", "ffmpeg"]

[deploy]
root = "server"
watchPatterns = ["server/**"]
startCommand = "node index.js"
